#!/bin/sh
for file in libinfgtk/resources/ui/*.ui; do
	intltool-extract --type="gettext/glade" $file
	sed -i -e 's/char \*s = //' ${file}.h
	git add ${file}.h
done

grep "_(" libinfinity libinftext libinfgtk libinftextgtk infinoted -R | \
	sed -e 's/:.*//' | grep -v matches | uniq | sort > po/POTFILES.in
