N_("Issued To");
N_("Common Name:");
N_("Organization:");
N_("Organizational Unit:");
N_("Serial Number:");
N_("Issued By");
N_("Validity");
N_("Issued On:");
N_("Expires On:");
N_("Fingerprints");
N_("SHA-1 Fingerprint:");
N_("SHA-256 Fingerprint:");
